[package]
name = "dungeon-generator"
version = "0.1.0"
authors = ["Nicholas Mc-Donnell <N9199@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "^0.7"
num = "^0.2"

